# Generated by Django 4.1.10 on 2023-07-27 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fullname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperListModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_scraper', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('last_run', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loginmodel')),
            ],
        ),
    ]
