# Generated by Django 4.1.10 on 2023-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperListModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_scraper', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
